### ISSUE TITLE
recipes.dictionary.min.js is empty

### ISSUE THREAD

**Issue by andrey-zakharov** [kevinta893/factorio-recipes-json#1]
https://kevinta893.github.io/factorio-recipes-json/recipes.dictionary.min.json 
is empty as new map in factorio

**Comment by kevinta893** [comment]
Thanks for the issue. The recipes.dictionary.min.json file is not empty anymore due to a minor error in the Travis CI build script.

Also to be clear, the JSON data is meant to help build web visualizations of the game's recipies.
